service: enterprise-serverless-playground
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs16.x
  stage: test
  region: us-east-1

functions:
  hello:
    handler: src/hello.handler
    events:
      - http:
          method: get
          path: /hello
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: EnterpriseCognitoAuthorizer
            scopes:
              - Something/hello

resources:
  Resources:
    EnterpriseCognitoAuthorizer:
      DependsOn:
        - ApiGatewayRestApi
      Type: AWS::ApiGateway::Authorizer
      Properties:
        IdentitySource: method.request.header.Authorization
        Name: cognito-authorizer
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - ${ssm:/cognito/client-pool-arn/${sls:stage}}
        RestApiId:
          Ref: ApiGatewayRestApi

    EnterprisePlaygroundResourceServer:
      Type: AWS::Cognito::UserPoolResourceServer
      Properties:
        # TODO: This should be the URL for Enterprise, not this. How can we get that?
        Identifier: Something
        Name: ${self:service}
        Scopes:
          - ScopeName: hello
            ScopeDescription: say hello
        UserPoolId: ${ssm:/cognito/client-pool-id/${sls:stage}}
